### ISSUE TITLE
Issue with running app

### ISSUE THREAD

**Issue by FilJed** [moses-palmer/virtual-touchpad#4]
Hello Moses,

After installing virtualtouchpad I run it and got this:

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\jedy\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\jedy\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jedy\AppData\Local\Programs\Python\Python37\lib\site-packages\pystray\_base.py", line 181, in setup_handler
    setup(self)
  File "C:\Users\jedy\AppData\Local\Programs\Python\Python37\lib\site-packages\virtualtouchpad\__main__.py", line 181, in setup
    main_server.start()
  File "C:\Users\jedy\AppData\Local\Programs\Python\Python37\lib\site-packages\virtualtouchpad\__init__.py", line 55, in start
    port=configuration.SERVER_PORT)
  File "C:\Users\jedy\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\web.py", line 50, in run_app
    loop = asyncio.get_event_loop()
  File "C:\Users\jedy\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.`

So it is not working as it should. Tried this on windows 10 with python 3.7 installed.

**Comment by vaibhavkumar049** [comment]
Yes I am facing the same issue

**Comment by MananGandhi1810** [comment]
i too am facing the same problem

**Comment by blacbrue** [comment]
Me too
`ERROR:virtualtouchpad:An unhandler exception occurred in main
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\v
irtualtouchpad\__main__.py", line 184, in start
    with _announcer(address, args.port):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\contextlib.py",
 line 113, in __enter__
    return next(self.gen)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\v
irtualtouchpad\__main__.py", line 125, in _announcer
    zc.register_service(info)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\z
eroconf\__init__.py", line 2496, in register_service
    self._broadcast_service(info)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\z
eroconf\__init__.py", line 2536, in _broadcast_service
    DNSText(info.name, _TYPE_TXT, _CLASS_IN | _CLASS_UNIQUE, info.other_ttl, inf
o.text), 0
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\z
eroconf\__init__.py", line 648, in __init__
    assert isinstance(text, (bytes, type(None)))
AssertionError`
